// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfBkBfgmrSQtv8lHwZKnQWpcr1zQ_BtPk',
    appId: '1:739492298588:web:8f3e06c4f4edad2e074b99',
    messagingSenderId: '739492298588',
    projectId: 'app-packtrack-c8d8e',
    authDomain: 'app-packtrack-c8d8e.firebaseapp.com',
    storageBucket: 'app-packtrack-c8d8e.firebasestorage.app',
    measurementId: 'G-S5YDDWBHGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjhSWkbSiN10YEuB_mDurFRKgJMnj1F5M',
    appId: '1:739492298588:android:3312dc9924cabe18074b99',
    messagingSenderId: '739492298588',
    projectId: 'app-packtrack-c8d8e',
    storageBucket: 'app-packtrack-c8d8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ_XNM_8iA3qW1Q_81EXqvx1myyuQydBA',
    appId: '1:739492298588:ios:de9dc0799b11a107074b99',
    messagingSenderId: '739492298588',
    projectId: 'app-packtrack-c8d8e',
    storageBucket: 'app-packtrack-c8d8e.firebasestorage.app',
    iosBundleId: 'com.example.appPacktrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ_XNM_8iA3qW1Q_81EXqvx1myyuQydBA',
    appId: '1:739492298588:ios:de9dc0799b11a107074b99',
    messagingSenderId: '739492298588',
    projectId: 'app-packtrack-c8d8e',
    storageBucket: 'app-packtrack-c8d8e.firebasestorage.app',
    iosBundleId: 'com.example.appPacktrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfBkBfgmrSQtv8lHwZKnQWpcr1zQ_BtPk',
    appId: '1:739492298588:web:77a9b867ea837fc4074b99',
    messagingSenderId: '739492298588',
    projectId: 'app-packtrack-c8d8e',
    authDomain: 'app-packtrack-c8d8e.firebaseapp.com',
    storageBucket: 'app-packtrack-c8d8e.firebasestorage.app',
    measurementId: 'G-W7D9V744DN',
  );

}